### ISSUE TITLE
Question about the number of data (ECInstruct)

### ISSUE THREAD

**Issue by yelobean** [ninglab/eCeLLM#1]
Hello. I found your research very interesting. And,, I have one question about ECInstruct.

When checking Hugging Face or the paper, it's stated that the ECInstruct Dataset contains a total of 116,528 data points. However, when looking at the json file provided by Hugging Face, there are 265,562 data points. Could you please explain the reason for this difference?

**Comment by xinyiling** [comment]
Thanks for your interest. For better reproducibility, besides the ECInstruct dataset, we put all the data used in various analyses in Hugging Face. That is, the dataset in Hugging Face comprises the ECInstruct dataset, data samples with the seed instruction and unseen instruction as used in the analysis of Section 6.3 and G.1, and data samples used for 1-shot evaluation. If you are only interested in the ECInstruct dataset, please refer to the following code to extract the data:
```
from datasets import load_dataset
import pandas as pd
dataset = pd.DataFrame(load_dataset("NingLab/ECInstruct")['train'])
default_dataset = dataset[(dataset['setting'] == 'IND_Diverse_Instruction') | (dataset['setting'] == 'OOD_Diverse_Instruction')]
```

**Comment by xinyiling** [comment]
We also updated the README file in Hugging Face to clarify

**Comment by yelobean** [comment]
Thanks for your kind answer!
