### ISSUE TITLE
'split' column is missing

### ISSUE THREAD

**Issue by yelobean** [ninglab/eCeLLM#2]
Hello. I found your research very interesting. And,, I have one question about ECInstruct.

Three days ago, when I download your data from huggingface, ECInstruct had the "split" column.
Thus, I can divide data to train,val,test.

However, after you modified data (2 days ago), I cannot access the "split" column on ECInstruct and I cannot divide data.

Could you add "split" column on your ECInstruct data?

**Comment by xinyiling** [comment]
Thanks for the reminder. We have updated the ECInstruct data now.
