### ISSUE TITLE
Where can I find train.json and valid.json

### ISSUE THREAD

**Issue by fsebastian93** [ninglab/eCeLLM#3]
Hi, could you help me with this? I tried to replicate but i got nan in eval_loss. So maybe I replicate train.json and valid.json wrong. Thanks

**Comment by xinyiling** [comment]
Of course. how did you replicate train.json and valid.json?

**Comment by fsebastian93** [comment]
Just load dataset.json from huggingface and filter split="train" and output to train.json from pandas, same from valid.json. But I see that maybe I so do this (I saw in inference commits) instead to_json from pandas:

    dataset = load_dataset("NingLab/ECInstruct")["train"]
    instructions, inputs, options = [], [], []
    for data in dataset:
        if data["split"] == "test" and data["task"] == task and data["setting"] == setting:
            instructions.append(data["instruction"])
            inputs.append(data["input"])
            options.append(data["options"])

Thanks so much.

**Comment by xinyiling** [comment]
Thanks for the question. Our current `finetune` files load train.json and val.json from [Google Drive](https://drive.google.com/drive/u/0/folders/1IaWM4o6GpqEmkGGhdXrZ0MMybpvpi5OZ). We will update the code for loading the data from huggingface later. If you'd like to load data from huggingface, please run
```python
from datasets import load_dataset
import json

train = []
dataset = load_dataset("NingLab/ECInstruct")["train"]
for data in dataset:
    if data["split"] == "train" and data["setting"] == "IND_Diverse_Instruction":
        train.append({
            "instruction": data["instruction"],
            "input": data["input"],
            "options": data["options"],
            "output": data["output"]
        })
with open("train.json", 'w') as f:
    json.dump(train, f, indent=4)
```
Similarly for val.json. Please feel free to contact us if you have any further questions.

**Comment by fersebas** [comment]
Thanks so much!! Verty helpful, I will try it :)

**Comment by fsebastian93** [comment]
Now I have this error:
Traceback (most recent call last):
  File "/workspace/eCeLLM/finetune.py", line 356, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/eCeLLM/finetune.py", line 297, in train
    train_data = data["train"].shuffle().map(generate_and_tokenize_prompt)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2795, in __getitem__
    return self._getitem(key)
  File "/usr/local/lib/python3.10/dist-packages/datasets/arrow_dataset.py", line 2779, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 580, in query_table
    _check_valid_column_key(key, table.column_names)
  File "/usr/local/lib/python3.10/dist-packages/datasets/formatting/formatting.py", line 520, in _check_valid_column_key
    raise KeyError(f"Column {key} not in the dataset. Current columns in the dataset: {columns}")
KeyError: "Column train not in the dataset. Current columns in the dataset: ['instruction', 'input', 'few_shot_example', 'options', 'setting', 'split', 'task', 'output', '__index_level_0__']"

**Comment by xinyiling** [comment]
Try to use:
```python
train_data = data.shuffle().map(generate_and_tokenize_prompt)
val_data = dev_data.shuffle().map(generate_and_tokenize_prompt)
```

**Comment by fsebastian93** [comment]
It works, thank you
