### ISSUE TITLE
Problem with NVIDIA T4 GPU inference

### ISSUE THREAD

**Issue by fsebastian93** [ninglab/eCeLLM#4]
Hi again,

I tried to make inference with finetuned model and I got this error:

`ValueError: We need an `offload_dir`to dispatch this model according to this`device_map`, the following submodules need to be offloaded: base_model.model.model.layers.27, base_model.model.model.layers.28, base_model.model.model.layers.29, base_model.model.model.layers.30, base_model.model.model.layers.31, base_model.model.model.norm, base_model.model.lm_head.`

Any help? I tried to do merge and unload, but it doesnt work either. :(

**Comment by BoPeng112** [comment]
Hi. 

I believe you got this error because the T4 GPU does not have sufficient memory to load the model. You might consider using quantization (https://huggingface.co/docs/transformers/en/main_classes/quantization).

**Comment by fsebastian93** [comment]
Thanks so much.
