### ISSUE TITLE
torch.bfloat16 o torch.float16

### ISSUE THREAD

**Issue by fsebastian93** [ninglab/eCeLLM#6]
Hi, I have another question why the code is with torch.bfloat16  and huggingface model is on torch.float16?
<img width="462" alt="image" src="https://github.com/ninglab/eCeLLM/assets/97440975/a7f7a0ed-3642-45ff-906d-d9378bfcc33a">

For NVIDIA T4 we should use float16, isn't? Thanks.

**Comment by BoPeng112** [comment]
Yes. I think T4 does not support bfloat16 so you may want to use float16.

**Comment by fsebastian93** [comment]
Thanks
