### ISSUE TITLE
Missing adapter_config.json in HF

### ISSUE THREAD

**Issue by poppybrown** [ninglab/eCeLLM#7]
Dear authors,
First of all congratulations on your work, it is very helpful.

I intend to use the ecellm-m model from HF, but when I donwload the model and run inference.sh,it has error "ValueError: Can't find 'adapter_config.json'"

**Comment by xinyiling** [comment]
Thanks for your question. The model in HF is uploaded after merging the fine-tuned LORA parameters with the base model. The <code>inference.sh</code> is used for the model training from scratch. Please run <code>inference_merge.sh</code> instead to use the model from HF. We also update the <code>README.md</code> for better clarification.

**Comment by ninglab** [comment]
[like]  Ning, Xia reacted to your message:
________________________________
