### ISSUE TITLE
ValueError when running finetune-t5

### ISSUE THREAD

**Issue by pjc9845x** [ninglab/eCeLLM#8]
Hi, I have this error

`
ValueError: Target modules {'up_proj', 'down_proj', 'gate_proj'} not found in the base model. Please check the target modules and try again.
`

when trying to run.

`
python finetune_T5.py google/flan-t5-xl
`

Did I do something wrong?

**Comment by xinyiling** [comment]
Please try to replace "finetune.py" with "finetune_T5.py" in line 55 of the `finetune.sh` file, and run `./finetune.sh 1 Flan-T5-XL 1k`.
