### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by dddddjcole** [ninglab/eCeLLM#9]
Hello, is there a corresponding Chinese data set

**Comment by dddddjcole** [comment]
Hello! I have some questions about datasets. Can you help me with them?

What does 'Product_Substitute_Identification' mean?
for example:
     query : "pack of hotwheels" 
     product : "Just Play Hot Wheels Ready to Race Car Builder, 29 Pieces" 
     label:No

     query : "diamond earrings for men" 
     product : "Dangle cross earrings in Sterling Silver with CZ diamonds - Handmade in the USA" 
     label: No
Under what standards will it be considered correct?

**Comment by xinyiling** [comment]
We conduct the product substitute identification task following the paper [Shopping Queries Dataset: A Large-Scale ESCI Benchmark for Improving Product Search](https://arxiv.org/abs/2206.06588), which breaks down the product-query relevance into the four classes (Exact, Substitute, Complement, and Irrelevant). 
As defined in this paper, the product substitute identification task requires the model to identify if the product is somewhat relevant, i.e., it fails to fulfill some aspects of the query but the product can be used as a functional substitute (e.g., fleece for a “sweater” query).
